balloon/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from balloon.apps import BalloonConfig
from balloon.views import BalloonListView, BalloonCrateView, ClientCreateView, ClientListView

app_name = BalloonConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('balloon_list/', BalloonListView.as_view(), name='balloon-list'),
    path('balloon_create/', BalloonCrateView.as_view(), name='balloon-create'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('balloon.urls', namespace='balloon')),
    path('rent/', include('rent.urls', namespace='rent')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/urls.py
from rent.apps import RentConfig

app_name = RentConfig.name

urlpatterns = []

balloon/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=100, verbose_name="Имя клиента")
    phone = models.CharField(max_length=10, unique=True, verbose_name="Номер телефона")
    firm = models.CharField(max_length=100, null=True, blank=True, verbose_name='Название фирмы')

    def __repr__(self):
        return f'<Client: {self.name}, phone: {self.phone}>'

    def __str__(self):
        return self.phone

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

class BalloonType(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Наименование типа баллона')

    def __repr__(self):
        return f'<BalloonType: {self.name}>'

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип баллона'
        verbose_name_plural = 'Тип баллонов'


class Balloon(models.Model):
    class StatusChoices(models.TextChoices):
        ACCEPTED_EMPTY = 'EMPTY', 'Принят пустой'
        AT_REFUELING = 'AT-REFUELING', 'Отправлен на заправку'
        ACCEPTED_FULL = 'ACCEPTED-FULL', 'Принят полный'
        AT_OWNER = 'AT-OWNER', 'У владельца'

    number = models.IntegerField(verbose_name='Номер баллона')
    type = models.ForeignKey(BalloonType, on_delete=models.CASCADE, verbose_name='Тип баллона')
    photo = models.ImageField(upload_to='media/balloon', null=True, blank=True)
    produced_at = models.DateField(verbose_name='Дата производства баллона')
    volume = models.IntegerField(verbose_name='обьем баллона')
    owner = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Владелец баллона')
    status = models.CharField(max_length=14,
                              choices=StatusChoices.choices,
                              default=StatusChoices.ACCEPTED_EMPTY,
                              verbose_name='Статус'
                              )

    def get_status_name(self):
        return dict(self.StatusChoices.choices)[self.status]

    def __str__(self):
        return f'<Balloon: {self.number}>'

    class Meta:
        verbose_name = 'Баллон'
        verbose_name_plural = 'Баллоны'

rent/models.py
from django.db import models

from balloon.models import BalloonType, Client


class Rent(models.Model):
    type = models.ForeignKey(BalloonType, on_delete=models.CASCADE, verbose_name='Тип баллона')
    owner = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент')
    count = models.IntegerField(verbose_name='Количество')
    volume = models.IntegerField(verbose_name='Обьем')
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(verbose_name='Дата окончания', null=True, blank=True)

    class Meta:
        verbose_name = 'Аренда'
        verbose_name_plural = 'Аренда'

balloon/forms.py
from django import forms

from balloon.models import Balloon, Client


class BalloonForm(forms.ModelForm):
    class Meta:
        model = Balloon
        fields = '__all__'

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = '__all__'

balloon/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView

from balloon.forms import BalloonForm, ClientForm
from balloon.models import Balloon, Client


class ClientCreateView(CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('balloon:client_list')

class ClientListView(ListView):
    model = Client


class BalloonCrateView(CreateView):
    model = Balloon
    success_url = reverse_lazy('balloon:balloon-list')
    form_class = BalloonForm




class BalloonListView(ListView):
    model = Balloon

class BalloonUpdateView(UpdateView):
    model = Balloon
    success_url = reverse_lazy('ballon:balloon-list')

class BalloonDeleteView(DeleteView):
    model = Balloon
    success_url = reverse_lazy('ballon:balloon-list')

rent/views.py
from django.shortcuts import render

# Create your views here.

balloon/templates/balloon/balloon_form.html
{% extends 'balloon/base.html' %}
{% block content %}
<div class="login-box center">
    {% if object %}
    <h1 class="ad_list_title">Редактирование записи</h1>
    {% else %}
    <h1 class="ad_list_title">Создание записи</h1>
    {% endif %}
    <form class="row" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="login-btn">Отправить</button>
    </form>
</div>
{% endblock %}

balloon/templates/balloon/balloon_list.html
{% load static %}
{% if messages %}
{% endif %}
{% include 'balloon/includes/head.html' %}
<div class="ad_list_top center">
    {% include 'balloon/includes/inc_menu.html' %}
    <div class="ad_list_titler">
        <h1 class="ad_list_title">Список обьявлений</h1>
    </div>
    <div class="alert" style="color: #FFFFFF">
        {% for message in messages %}
        <div class="alert-{{ message.tags }}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
</div>
<nav class="breadcrumbs center">
    <a href="#" class="breadcrumbs_link">Главная</a>
    {% if user.is_authenticated %}
    <a href="#" class="breadcrumbs_link">Добавить обьявление</a>
    {% endif %}
</nav>
<div class="center">
    <div class="border"></div>
</div>

<form method="GET">
    <div class="filter-box center" >
        <div>
            <label class="desc">Категория:</label>
            <select name="category" class="filter-box__select">
                <option value="">Все категории</option>
                {% for category in categories %}
                <option value="{{ category }}"
                        {% if category == selected_category %}selected{% endif %}>{{ category }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label class="desc">Состояние:</label>
            <select name="condition" class="filter-box__select">
                <option value="">Все состояния</option>
                <option value="{{ 'N' }}" {% if selected_condition == 'N' %}selected{% endif %}>Новое</option>
                <option value="{{ 'U' }}" {% if selected_condition == 'U' %}selected{% endif %}>Б/У</option>
            </select>
        </div>
        <button type="submit" class="ad_card_button" style="height: 30px;">Применить фильтр</button>
    </div>
    <div class="center">
        <div class="border"></div>
    </div>
</form>

<div class="ad_box center">
    {% for balloon in object_list %}
    <div class="ad">
        <img src="{{ balloon.photo }}" alt="" class="ad_img">
        <div class="ad_body">
            <h3 class="ad_title">{{ balloon.number }}</h3>
            <p class="ad_description">{{ balloon.get_status_name }}</p>
            <a href="#"><button class="ad_card_button">Подробнее</button></a>
        </div>
    </div>
    <div class="border"></div>
    {% empty %}
    <h1 class="ad_list_title">Товары не найдены</h1>
    {% endfor %}
</div>
</body>

balloon/templates/balloon/base.html
{% load static %}

{% include 'balloon/includes/head.html' %}

<div class="top center">
    {% include 'balloon/includes/inc_menu.html' %}

    <div class="titler_base" id="titlerBase">
        <h1 class="title">Второй шанс вашим вещам — площадка обмена</h1>
        <p class="desc">Обменивайте и продавайте любимые вещи легко и безопасно. Дарим вещам новую жизнь, а вам —
            экономию и экологичное потребление. Присоединяйтесь к сообществу осознанных покупателей!</p>
    </div>
    {% block content %}

    {% endblock %}
</div>

<script src="{% static 'script.js' %}"></script>
</body>
</html>

balloon/templates/balloon/client_form.html
{% extends 'balloon/base.html' %}
{% block content %}
<div class="login-box center">
    {% if object %}
    <h1 class="ad_list_title">Редактирование записи</h1>
    {% else %}
    <h1 class="ad_list_title">Создание записи</h1>
    {% endif %}
    <form class="row" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="login-btn">Отправить</button>
    </form>
</div>
{% endblock %}

balloon/templates/balloon/client_list.html
{% extends 'balloon/base.html' %}
{% block content %}
<div class="login-box center">
  <table>
    <thead>
      <td>Имя</td>
      <td>Номер телефона</td>
      <td>Фирма</td>
    </thead>
    {% for client in object_list %}
    <tr>
      <td>{{ client.name }}</td>
      <td>{{ client.phone }}</td>
      <td>{{ client.firm }}</td>
    </tr>
    {% endfor %}
  </table>

</div>
{% endblock %}

balloon/templates/balloon/includes/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>

balloon/templates/balloon/includes/inc_menu.html
{% load static %}
<header>
    <nav class="top_menu center">
<!--        {% if not user.is_authenticated %}-->
<!--        <a href="{% url 'balloon:login' %}" class="header_link">Вход</a>-->
<!--        <a href="{% url 'balloon:register' %}" class="header_link">Регистрация</a>-->
<!--        {% else %}-->
<!--        <a href="#" onclick="sendPostRequest()" class="header_link">Выход</a>-->
<!--        <form id="myForm" action="{% url 'balloon:logout' %}" method="post" style="display:none;">-->
<!--            {% csrf_token %}-->
<!--        </form>-->
<!--        <script>-->
<!--            function sendPostRequest() {-->
<!--                document.getElementById('myForm').submit();-->
<!--            }-->
<!--        </script>-->
<!--        {% endif %}-->
    </nav>
<!--    <form method="get" action="{% url 'balloon:balloon-list' %}">-->
<!--        <input placeholder="Поиск..." type="text" name="q" value="{{ request.GET.q }}" class="header_input">-->
<!--        <button type="submit" style="display: none"></button>-->
<!--    </form>-->
    <script>
        document.querySelector('input[name="q"]').addEventListener('keyup', function (event) {
            if (event.key === "Enter") {
                event.preventDefault();
                this.form.submit();
            }
        });
    </script>
    <nav class="top_menu center">
<!--        <a href="{% url 'balloon:balloon-list' %}" class="header_link">Обьявления</a>-->
<!--        <a href="{% url 'balloon:balloon-list' %}" class="header_link">Мои предложения</a>-->
    </nav>
</header>